### ISSUE TITLE
skip `Persistent` paremeter

### ISSUE THREAD

**Issue by mstruebing** [sitegeist/Sitegeist.MagicWand#27]
Maybe it would be a good idea to add a feature which lets you skip the transfer of the `Data/Persistent` directory.
This would be useful if you only need a fresh database instead of the whole project data, especially in large projects.

**Comment by waldicom** [comment]
I've created a pull request that implements this feature: https://github.com/sitegeist/Sitegeist.MagicWand/pull/31

**Comment by grebaldi** [comment]
I'll close this one, because in https://github.com/sitegeist/Sitegeist.MagicWand/pull/31 it was determined that this issue is sufficiently addressed by proxy assets.
