### ISSUE TITLE
Escaping parameters for remote shell execution

### ISSUE THREAD

**Issue by freund0** [sitegeist/Sitegeist.MagicWand#33]
If e.g. the password of the db user on the remote server contains special characters as e.g. '$' the mysqldump command fails (mysql connection cannot be established). 

In the setup where I experienced difficulties with this, we are using a Jumphost (passed by ProxyCommand sshOption) and I had to double escape the special character in the password in order to make a successful clone.

**Comment by DrillSergeant** [comment]
Facing same issue. We have a password containing & which causes the shell-command to fail. If the password would be wrapped by quotes the db commands would work

**Comment by DrillSergeant** [comment]
Update the problem seems only to exist when executing the drop database in the restore-command. In all other mysql commands the parameters are wrapped into quotes already.
